baseURL = 'https://forgoodweightloss.com/'
languageCode = 'en-us'
title = 'For Good'

enableRobotsTXT = true

[params]
  defaultButtonClasses = "btn btn-outline-pink border-2 mb-1 rounded-pill"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"