backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - label: "Landing Pages"
    name: "sitePages"
    create: false
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "data/homepage.yml"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "meta_description", widget: "text", hint: "Used by search engines.", required: false }
          - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
          - { label: "Featured Image Alt", name: "featured_image_alt", widget: "string", required: false }
          - label: "Hero"
            name: "hero"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - { label: "Lede", name: 'lede', widget: 'text' }
              - { label: "Photo", name: "photo", widget: "image" }
              - { label: "Photo Alt", name: 'alt', widget: 'text' }
              - label: "Call to Action"
                name: "cta"
                widget: list
                required: false
                fields:
                  - { label: "Button Text", name: "button_text", widget: "string" }
                  - { label: "Size", name: "size", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
          - label: "Blob"
            name: blob
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - label: "Tries"
                name: "tries"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false }
                  - { label: "Copy", name: "copy", widget: "string" }
                  - { label: "Size", name: "size", widget: "number", required: false }
              - label: "Before and After"
                name: "before_after"
                widget: "object"
                collapsed: true
                fields:
                  - { label: "Before", name: "before", widget: "image" }
                  - { label: "After", name: "after", widget: "image" }
                  - { label: "After After", name: "after_after", widget: "image" }
              - { label: "Heading 2", name: "heading_2", widget: "string" }
              - label: "Struggles"
                name: "struggles"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "Struggle", name: "struggle", widget: "string" }
              - { label: "CTA Heading", name: "cta_heading", widget: "string" }
              - label: "Call to Action"
                name: "cta"
                widget: list
                required: false
                fields:
                  - { label: "Button Text", name: "button_text", widget: "string" }
                  - { label: "Size", name: "size", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
          - label: "Ready to Give Up"
            name: "series_quit"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string", required: false }
                  - { label: "Copy", name: "copy", widget: "string" }
                  - { label: "Size", name: "size", widget: "number", required: false }
          - label: "Stats"
            name: "stats"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Super Heading", name: "super_heading", widget: "string" }
              - { label: "Heading", name: "heading", widget: "string" }
              - label: "Panels"
                name: "panels"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "Stat", name: "stat", widget: "string" }
                  - { label: "Copy", name: "copy", widget: "string" }
                  - label: "Logos"
                    name: "logos"
                    widget: "list"
                    collapsed: true
                    fields:
                      - { label: "Logo", name: "logo", widget: "image" }
                      - { label: "Alt Text", name: "alt", widget: "string" }
          - label: "Keep It Off"
            name: "keep_it_off"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "Item", name: "item", widget: "string" }
              - label: "Call to Action"
                name: "cta"
                widget: list
                required: false
                fields:
                  - { label: "Button Text", name: "button_text", widget: "string" }
                  - { label: "Size", name: "size", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
          - label: "Mission"
            name: "mission"
            widget: "object"
            collapsed: true
            fields:
              - label: "Badge"
                name: "badge"
                widget: "object"
                collapsed: true
                fields:
                  - { label: "SRC", name: "src", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Message", name: "message", widget: "text" }
          - label: "Find Your Soul Weight"
            name: "guides"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - label: "Guides"
                name: "guides"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    collapsed: true
                    fields:
                      - { label: "Item", name: "item", widget: "markdown" }
                  - { label: "Photo", name: "photo", widget: "image" }
                  - { label: "Photo Alt Text", name: "photo_alt", widget: "string" }
                  - label: "Badge"
                    name: "badge"
                    widget: "object"
                    collapsed: true
                    fields:
                      - { label: "SRC", name: "src", widget: "image" }
                      - { label: "Alt Text", name: "alt", widget: "string" }
                  - label: "Logos"
                    name: "logos"
                    widget: "list"
                    collapsed: true
                    fields:
                      - { label: "Logo", name: "logo", widget: "image" }
                      - { label: "Alt Text", name: "alt", widget: "string" }
          - label: "Average Loss"
            name: "average_loss"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Heading Bold", name: "heading_bold", widget: "string" }
              - label: "Profiles"
                name: "profiles"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "Photo", name: "photo", widget: "image" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Loss", name: "loss", widget: "string" }
  - name: 'backPages'
    label: 'Back Pages'
    folder: "content/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: false }
      - { label: 'Featured Image Alt', name: 'featured_image_alt', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Settings"
    name: "settings"
    create: false
    editor:
      preview: false
    files:
      - label: "Config"
        name: "config"
        file: "data/settings.yml"
        editor:
          preview: false
        fields:
          - { label: "Site Description", name: "description", widget: "text" }
          - label: "Site Menu"
            name: "site_menu"
            widget: "list"
            fields:
              - { label: "Menu Item", name: "menu_item", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
            required: false
          - label: "Footer Copy"
            name: "footer_copy"
            widget: "string"
            required: false
          - label: "Chat with us"
            name: "chat"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string", required: false }
          - label: "Phone"
            name: "phone"
            widget: "string"
            required: false
          - label: "Members"
            name: "members"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string", required: false }
          - label: "Social Media Accounts"
            name: "social_media_accounts"
            widget: "list"
            required: false
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "Username", name: "username", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string" }