backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - label: "Landing Pages"
    name: "sitePages"
    create: false
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "data/homepage.yml"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "meta_description", widget: "text", hint: "Used by search engines.", required: false }
          - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
          - { label: "Featured Image Alt", name: "featured_image_alt", widget: "string", required: false }
          - label: "Hero"
            name: "hero"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - { label: "Lede", name: 'lede', widget: 'text' }
              - { label: "Photo", name: "photo", widget: "image" }
              - { label: "Photo Alt", name: 'alt', widget: 'text' }
              - label: "Call to Action"
                name: "cta"
                widget: list
                required: false
                fields:
                  - { label: "Button Text", name: "button_text", widget: "string" }
                  - { label: "Size", name: "size", widget: "string", required: false }
                  - { label: "URL", name: "url", widget: "string", required: false }
  - label: "Settings"
    name: "settings"
    create: false
    editor:
      preview: false
    files:
      - label: "Config"
        name: "config"
        file: "data/settings.yml"
        editor:
          preview: false
        fields:
          - { label: "Site Description", name: "description", widget: "text" }
          - label: "Site Menu"
            name: "site_menu"
            widget: "list"
            fields:
              - { label: "Menu Item", name: "menu_item", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
            required: false
          - label: "Footer Copy"
            name: "footer_copy"
            widget: "string"
            required: false
          - label: "Chat with us"
            name: "chat"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string", required: false }
          - label: "Phone"
            name: "phone"
            widget: "string"
            required: false
          - label: "Members"
            name: "members"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string", required: false }
          - label: "Social Media Accounts"
            name: "social_media_accounts"
            widget: "list"
            required: false
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "Username", name: "username", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string" }